import '../models/farmer_model.dart';

/// Set to false once Firebase is configured (flutterfire configure).
const bool kDemoMode = true;

final List<FarmerModel> demoFarmers = [
  FarmerModel(
    id: 'demo-01',
    name: 'Ramesh Kumar Singh',
    phone: '9876543210',
    address: 'House No. 12, Near Panchayat Bhavan',
    village: 'Sundarpur',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    category: 'Agroforestry',
    subcategory: 'Silvopasture',
    landArea: 3.5,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 2)),
    status: 'Active',
    dynamicFields: {
      'treeSpecies': 'Teak, Neem',
      'treesPerAcre': '80',
      'plantationAge': '4',
      'certification': 'Plan Vivo',
      'carbonStock': '12.5',
    },
    landCoordinates: [
      {'lat': 26.8467, 'lng': 80.9462},
      {'lat': 26.8470, 'lng': 80.9475},
      {'lat': 26.8460, 'lng': 80.9480},
      {'lat': 26.8455, 'lng': 80.9465},
    ],
  ),
  FarmerModel(
    id: 'demo-02',
    name: 'Suresh Patel',
    phone: '9812345678',
    address: '45, Main Road, Opp. Post Office',
    village: 'Khandwa',
    district: 'Khandwa',
    state: 'Madhya Pradesh',
    category: 'Soil Carbon',
    subcategory: 'Cover Cropping',
    landArea: 5.0,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 5)),
    status: 'Active',
    dynamicFields: {
      'currentPractice': 'Cover Cropping',
      'baselineSOC': '0.8',
      'targetSOC': '1.5',
      'previousLandUse': 'Cropland',
      'measurementMethod': 'Lab Analysis (Walkley-Black)',
      'yearsInPractice': '2',
    },
  ),
  FarmerModel(
    id: 'demo-03',
    name: 'Anita Devi',
    phone: '9765432100',
    address: 'Ward No. 3, Gram Panchayat Office Road',
    village: 'Rampur',
    district: 'Sitapur',
    state: 'Uttar Pradesh',
    category: 'Biochar',
    subcategory: 'Wood Biochar',
    landArea: 1.2,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 8)),
    status: 'Active',
    dynamicFields: {
      'feedstockType': 'Wood / Woody Biomass',
      'productionMethod': 'Slow Pyrolysis',
      'applicationRate': '2.5',
      'carbonContent': '72',
      'applicationFrequency': 'Annual',
    },
  ),
  FarmerModel(
    id: 'demo-04',
    name: 'Mohan Lal Yadav',
    phone: '9654321098',
    address: 'Near Shiv Temple, Village Road',
    village: 'Barabanki',
    district: 'Barabanki',
    state: 'Uttar Pradesh',
    category: 'Agroforestry',
    subcategory: 'Alley Cropping',
    landArea: 2.8,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 12)),
    status: 'Active',
    dynamicFields: {
      'treeSpecies': 'Leucaena, Moringa',
      'treesPerAcre': '120',
      'intercrop': 'Sorghum, Cowpea',
      'plantationAge': '2',
      'certification': 'None',
    },
  ),
  FarmerModel(
    id: 'demo-05',
    name: 'Priya Kumari',
    phone: '9543210987',
    address: 'Block C, Agriculture Colony',
    village: 'Darbhanga',
    district: 'Darbhanga',
    state: 'Bihar',
    category: 'Soil Carbon',
    subcategory: 'No-till / Reduced Tillage',
    landArea: 0.75,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 15)),
    status: 'Active',
    dynamicFields: {
      'currentPractice': 'No-till / Reduced Tillage',
      'baselineSOC': '0.6',
      'targetSOC': '1.2',
      'previousLandUse': 'Degraded Land',
      'yearsInPractice': '3',
    },
  ),
  FarmerModel(
    id: 'demo-06',
    name: 'Vijay Shankar Gupta',
    phone: '9432109876',
    address: 'Plot No. 8, Krishak Nagar',
    village: 'Patna Rural',
    district: 'Patna',
    state: 'Bihar',
    category: 'Biochar',
    subcategory: 'Crop Residue Biochar',
    landArea: 1.5,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 20)),
    status: 'Inactive',
    dynamicFields: {
      'feedstockType': 'Crop Residue (Rice Husk, Straw)',
      'productionMethod': 'Gasification',
      'applicationRate': '3.0',
      'carbonContent': '65',
    },
  ),
  FarmerModel(
    id: 'demo-07',
    name: 'Kamla Bai Verma',
    phone: '9321098765',
    address: 'Tehsil Road, Near Bus Stand',
    village: 'Ujjain',
    district: 'Ujjain',
    state: 'Madhya Pradesh',
    category: 'Agroforestry',
    subcategory: 'Multi-strata Systems',
    landArea: 4.0,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 25)),
    status: 'Active',
    dynamicFields: {
      'treeSpecies': 'Bamboo, Mango, Jackfruit',
      'treesPerAcre': '200',
      'intercrop': 'Turmeric, Ginger',
      'plantationAge': '6',
      'certification': 'VCS / Verra',
      'carbonStock': '28.4',
    },
  ),
  FarmerModel(
    id: 'demo-08',
    name: 'Rajendra Prasad Mishra',
    phone: '9210987654',
    address: 'Village Center, Near School',
    village: 'Varanasi Rural',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'Soil Carbon',
    subcategory: 'Rotational Grazing',
    landArea: 6.5,
    landUnit: 'Acres',
    registrationDate: DateTime.now().subtract(const Duration(days: 30)),
    status: 'Active',
    dynamicFields: {
      'currentPractice': 'Rotational Grazing',
      'baselineSOC': '1.1',
      'targetSOC': '2.0',
      'previousLandUse': 'Grassland',
      'measurementMethod': 'Remote Sensing',
      'yearsInPractice': '5',
    },
  ),
];
